---
# tasks file for bluecat-ipam-rest
- name: Acquire IP Address
  include: acquire_ip.yml
  when: state == 'present' or state == 'acquire'
  delegate_to: localhost
  connection: local
  run_once: true

- name: Lookup IP Address
  include: lookup_ip.yml
  when: state == 'get' or state == 'lookup'
  delegate_to: localhost
  connection: local
  run_once: true

- name: Release IP Address
  include: release_ip.yml
  when: state == 'absent' or state == 'release'
  delegate_to: localhost
  connection: local
  run_once: true
